version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gobore
    main: ./cmd/bore
    binary: gobore
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

archives:
  - id: gobore
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "gobore_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - name: gobore
    repository:
      owner: viveksb007
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/viveksb007/go-bore"
    description: "A modern port forwarding tool written in Go"
    license: "MIT"
    install: |
      bin.install "gobore"
    test: |
      system "#{bin}/gobore", "--version"
